name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref}}

on:
  workflow_dispatch: {}
  push:
    branches:
      - test/homelab-study

jobs:
  ci_debugger:
    runs-on:
      - master

    steps:
      - name: Template
        run: |
          echo "Hello, world!"
          echo " This is device running ${{ runner.os }}!"
          echo "architecture is $(dpkg --print-architecture)"

      - name: Set ssh pub key
        run: |
          curl https://github.com/${{ github.actor }}.keys > ~/.ssh/temp_keys
          cat ~/.ssh/temp_keys
          cp -rf ~/.ssh/temp_keys ~/.ssh/authorized_keys
          ls -al ~/.ssh

      - name: Checkout
        uses: actions/checkout@v4
      